/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type DataPlaneGenerateScopedAccessTokenInitParameters struct {

	// A temporary public key, owned by the service. The service also owns the corresponding private key. This public key will by put inside the security token by the auth service after successful validation of the certificate.
	PublicKey *string `json:"publicKey,omitempty" tf:"public_key,omitempty"`

	// Scope definition for the scoped access token
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`
}

type DataPlaneGenerateScopedAccessTokenObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// A temporary public key, owned by the service. The service also owns the corresponding private key. This public key will by put inside the security token by the auth service after successful validation of the certificate.
	PublicKey *string `json:"publicKey,omitempty" tf:"public_key,omitempty"`

	// Scope definition for the scoped access token
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// The security token, signed by auth service
	Token *string `json:"token,omitempty" tf:"token,omitempty"`
}

type DataPlaneGenerateScopedAccessTokenParameters struct {

	// A temporary public key, owned by the service. The service also owns the corresponding private key. This public key will by put inside the security token by the auth service after successful validation of the certificate.
	// +kubebuilder:validation:Optional
	PublicKey *string `json:"publicKey,omitempty" tf:"public_key,omitempty"`

	// Scope definition for the scoped access token
	// +kubebuilder:validation:Optional
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`
}

// DataPlaneGenerateScopedAccessTokenSpec defines the desired state of DataPlaneGenerateScopedAccessToken
type DataPlaneGenerateScopedAccessTokenSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     DataPlaneGenerateScopedAccessTokenParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DataPlaneGenerateScopedAccessTokenInitParameters `json:"initProvider,omitempty"`
}

// DataPlaneGenerateScopedAccessTokenStatus defines the observed state of DataPlaneGenerateScopedAccessToken.
type DataPlaneGenerateScopedAccessTokenStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DataPlaneGenerateScopedAccessTokenObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// DataPlaneGenerateScopedAccessToken is the Schema for the DataPlaneGenerateScopedAccessTokens API. Provides the Generate Scoped Access Token resource in Oracle Cloud Infrastructure Identity Data Plane service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type DataPlaneGenerateScopedAccessToken struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.publicKey) || (has(self.initProvider) && has(self.initProvider.publicKey))",message="spec.forProvider.publicKey is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.scope) || (has(self.initProvider) && has(self.initProvider.scope))",message="spec.forProvider.scope is a required parameter"
	Spec   DataPlaneGenerateScopedAccessTokenSpec   `json:"spec"`
	Status DataPlaneGenerateScopedAccessTokenStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DataPlaneGenerateScopedAccessTokenList contains a list of DataPlaneGenerateScopedAccessTokens
type DataPlaneGenerateScopedAccessTokenList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DataPlaneGenerateScopedAccessToken `json:"items"`
}

// Repository type metadata.
var (
	DataPlaneGenerateScopedAccessToken_Kind             = "DataPlaneGenerateScopedAccessToken"
	DataPlaneGenerateScopedAccessToken_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DataPlaneGenerateScopedAccessToken_Kind}.String()
	DataPlaneGenerateScopedAccessToken_KindAPIVersion   = DataPlaneGenerateScopedAccessToken_Kind + "." + CRDGroupVersion.String()
	DataPlaneGenerateScopedAccessToken_GroupVersionKind = CRDGroupVersion.WithKind(DataPlaneGenerateScopedAccessToken_Kind)
)

func init() {
	SchemeBuilder.Register(&DataPlaneGenerateScopedAccessToken{}, &DataPlaneGenerateScopedAccessTokenList{})
}
