apiVersion: identity.oci.upbound.io/v1alpha1
kind: DataPlaneGenerateScopedAccessToken
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/dataplanegeneratescopedaccesstoken
  labels:
    testing.upbound.io/example-name: test_generate_scoped_access_token
  name: test-generate-scoped-access-token
spec:
  forProvider:
    publicKey: ${var.generate_scoped_access_token_public_key}
    scope: ${var.generate_scoped_access_token_scope}
