apiVersion: resourcemanager.oci.upbound.io/v1alpha1
kind: PrivateEndpoint
metadata:
  labels:
    testing.upbound.io/example-name: privatedndpoint_label_1
  name: privateendpoint1
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    description: "Test private endpoint"
    displayName: privateendpoint1
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: subnet_label_1
    vcnIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vcn_label_1
